### ISSUE TITLE
Weird look

### ISSUE THREAD

**Issue by iambeingtracked** [hexoctal/st-undercurl#4]
![thing](https://github.com/hexoctal/st-undercurl/assets/94642304/1fbd9003-f9cc-4b45-b77f-37abf9afa312)
Left: Alacritty
Right: st
I think it looked better on the screenshots provided in the repo. I first thought it might be because of antialias and autohint but it's the same with them enabled and disabled. The font is a nerd font patched Cascadia Code.

**Comment by derriche-massinissa** [comment]
Sorry for the very late reply.
Yes, this look is due to X not providing any anti-aliasing methods to draw lines. Actually it doesn't even have any methods to draw lines, I had to generate the squiggly pattern by drawing pixel by pixel on a separate buffer. I would recommend you using the capped line style instead (which should be the default), it looks much better too.
